// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ0V4pkp6iXq6A7lZb0eOeoxU1nw-jr4o',
    appId: '1:202257291519:web:fa358b5750f81f322214ca',
    messagingSenderId: '202257291519',
    projectId: 'bravzsupatips',
    authDomain: 'bravzsupatips.firebaseapp.com',
    databaseURL: 'https://bravzsupatips-default-rtdb.firebaseio.com',
    storageBucket: 'bravzsupatips.appspot.com',
    measurementId: 'G-01R0DVLMC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDls2ULE5Mz14eCiIUSJxL4QkyBEXPsVn8',
    appId: '1:202257291519:android:4f05436466b1d2632214ca',
    messagingSenderId: '202257291519',
    projectId: 'bravzsupatips',
    databaseURL: 'https://bravzsupatips-default-rtdb.firebaseio.com',
    storageBucket: 'bravzsupatips.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfb6BRf2gjUyzAToR7RS1_3y5CRlqEsc',
    appId: '1:202257291519:ios:bef5137b2c0ca87c2214ca',
    messagingSenderId: '202257291519',
    projectId: 'bravzsupatips',
    databaseURL: 'https://bravzsupatips-default-rtdb.firebaseio.com',
    storageBucket: 'bravzsupatips.appspot.com',
    androidClientId: '202257291519-sde7r7elovoans7ij0m8andn99muevvi.apps.googleusercontent.com',
    iosClientId: '202257291519-ss1r4elo32ldhl089jolm4a35t476fvt.apps.googleusercontent.com',
    iosBundleId: 'com.baszman.site',
  );
}
